# jekyll-rtd-theme
# https://github.com/rundocs/jekyll-rtd-theme

# remote_theme: rundocs/jekyll-rtd-theme
# remote_theme: JV-conseil-Internet-Consulting/jekyll-rtd-theme@single
# remote_theme: JV-conseil-Internet-Consulting/jekyll-rtd-theme
remote_theme: https://github.com/carlosperate/jekyll-theme-rtd

# Aux links for the upper right navigation
# aux_links:
#   "View PyPi package":
#     - "//pypi.org/project/django-azure-active-directory-signin/"
